name: Pages Deploy

on:
  push:
    branches:
      - v2.0.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: v2.0.0

    - name: Install Dependencies
      run: npm install

    - name: Build the App
      run: npm run craco build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.2
      with:
        branch: gh-pages
        folder: ./
